// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsEVGyMNu7eN3lNyveXv77TM7yv1ONSs4',
    appId: '1:499884078406:android:17fe7f0560d5d50c322147',
    messagingSenderId: '499884078406',
    projectId: 'fruit-shop-c8538',
    storageBucket: 'fruit-shop-c8538.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYJ_DbK4qZU8ZLnGot4WvIMUVg-pyY2xQ',
    appId: '1:499884078406:ios:1604d2a559a365c5322147',
    messagingSenderId: '499884078406',
    projectId: 'fruit-shop-c8538',
    storageBucket: 'fruit-shop-c8538.firebasestorage.app',
    androidClientId: '499884078406-3rdnuhp4m5b4uc9i277ubobfutfjmtjf.apps.googleusercontent.com',
    iosClientId: '499884078406-4edij0fipeve8iqs59g1psd495fknlm1.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitShop',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB85sQgbSXh-2YXWaDkmNaRfGmGCQD75fM',
    appId: '1:499884078406:web:5ef65443954c27ff322147',
    messagingSenderId: '499884078406',
    projectId: 'fruit-shop-c8538',
    authDomain: 'fruit-shop-c8538.firebaseapp.com',
    storageBucket: 'fruit-shop-c8538.firebasestorage.app',
    measurementId: 'G-2DY8775C4E',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYJ_DbK4qZU8ZLnGot4WvIMUVg-pyY2xQ',
    appId: '1:499884078406:ios:1604d2a559a365c5322147',
    messagingSenderId: '499884078406',
    projectId: 'fruit-shop-c8538',
    storageBucket: 'fruit-shop-c8538.firebasestorage.app',
    androidClientId: '499884078406-3rdnuhp4m5b4uc9i277ubobfutfjmtjf.apps.googleusercontent.com',
    iosClientId: '499884078406-4edij0fipeve8iqs59g1psd495fknlm1.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB85sQgbSXh-2YXWaDkmNaRfGmGCQD75fM',
    appId: '1:499884078406:web:864b2465d1f56de8322147',
    messagingSenderId: '499884078406',
    projectId: 'fruit-shop-c8538',
    authDomain: 'fruit-shop-c8538.firebaseapp.com',
    storageBucket: 'fruit-shop-c8538.firebasestorage.app',
    measurementId: 'G-C2G1JP3MPK',
  );

}